group_imports = "StdExternalCrate"
imports_granularity = "Crate"
imports_layout = "Vertical"
fn_params_layout = "Vertical"
merge_derives = true
brace_style = "AlwaysNextLine"
doc_comment_code_block_width = 100
format_code_in_doc_comments = true
comment_width = 80
